### ISSUE TITLE
Excluding Libraries 

### ISSUE THREAD

**Issue by jpartain89** [Hellowlol/bw_plex#105]
Is there any possibility that there could be a setting added to, say, the config file, where we could tell bw_plex to exclude a specific library?

Like, lets say we only want the TV shows processed: no movies, no personal videos, etc. etc. Should that not be an easily-obvious option?

**Comment by Hellowlol** [comment]
It not possible to exlude based on sections. As for movies just disable check_credits, create_edl etc. You can also exclude based on ratingkeys.
