### ISSUE TITLE
Problems with resume

### ISSUE THREAD

**Issue by Inrego** [Hellowlol/bw_plex#122]
Quite often if I resume an episode, bw_plex will jump to the intro ending. That's quite unwanted, since I was expecting to resume in the middle of an episode.

**Comment by Hellowlol** [comment]
Hi! That is a unwanted behavior.

So when you say resume, do you mean that you have stopped playback somewhere in a episode and then try to start of from that point? Or that you have started a episode, hit pause and then it goes back to the end of the intro?

Can you post log some logs where this happened?

**Comment by Inrego** [comment]
I will post logs when I see it again. But right now I'm facing more severe annoyances, which I will make another ticket about.

**Comment by Hellowlol** [comment]
Closing this for now, reopen with log is you still have this issue
