### ISSUE TITLE
remaps are not working

### ISSUE THREAD

**Issue by gadgetusaf** [Hellowlol/bw_plex#129]
Running in docker wiht my media folder path mounted to /mnt/unionfs/Media/ 
MY media on the Plex server is M:\ 
Is this correct?

/mnt/unionfs/Media/ = M:\\

**Comment by gadgetusaf** [comment]
I notice 
`
Checking if we can reach ShowName.s01e01 directly
Downloading from pms..
`

**Comment by Hellowlol** [comment]
Try M:\\

**Comment by gadgetusaf** [comment]
made the change but it is still downloading from pms. I have confirmed that the docker container can see the media folder

**Comment by Hellowlol** [comment]
Did you use two \?

**Comment by gadgetusaf** [comment]
No I did not.
`[tv]
# This lets bw_plex know that its suppose to analyze the video for credits
check_credits = False
# Setting this to 'stop' will stop playback when credits starts.
# if set to seek it will
check_credits_action = 
# This will start the next available episode
## NOTE: check_credits_action need to be `stop` for this to work.
check_credits_start_next_ep = True
credits_delay = 0
check_credits_sec = 120
check_for_theme_sec = 600
check_intro_ffmpeg_sec = 600
process_recently_added = True
process_deleted = False
# Options: 'all', 'tvtunes', 'plex', 'youtube'
theme_source = all
words = previously on, last season, last episode
create_edl = False
edl_action_type = 3
create_chapters = False

[hashing]
check_frames = False
#every_n = not in use atm.


# remaps can use used to location set a partial location
# this is usefull if bw_plex is running on another computer.
# the key is the path plex user and the value is the computer running
# bw_plex. Ex:
# /tvseries/ = W:\
[remaps]
/mnt/unionfs/Media/ = M:\

`

**Comment by Hellowlol** [comment]
Ok. You need to use two of them.

**Comment by gadgetusaf** [comment]
I also tried with two \ but that did not work either.


On May 22, 2020, at 09:11, Steffen Fredriksen <notifications@github.com>
wrote:

﻿

Ok. You need to use two of them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Hellowlol/bw_plex/issues/129#issuecomment-632682903>,
or unsubscribe

**Comment by Hellowlol** [comment]
This is how it its in my config file. 
````
[remaps]
/tvseries/ = W:\\
````

I cant see any reason why this should fail. Check the path that the files have listed in the webui or using plexapi.
