### ISSUE TITLE
Enable whole show / season processing for bw_plex process

### ISSUE THREAD

**Issue by KevinDenis** [Hellowlol/bw_plex#131]
Currently, using `bw_plex process --name foo` requires the user to select an episode at the `Select episodes:` prompt. I did not find a way to enable the possibility to process _all_ listed episodes.
A nice feature would be the ability to process a whole season.

**Comment by Hellowlol** [comment]
The select support python slicing. The format is start, end, step

So say you want all episodes you just do ````::`````instead of a number.
