### ISSUE TITLE
Server Error when trying to skip credits

### ISSUE THREAD

**Issue by Juxsta** [Hellowlol/bw_plex#141]
I’m running this using the docker container on unraid. Everything works except for when trying to skip and into/outro. I receive the following error.
`plexapi.exceptions.BadRequest: (500) internal_server_error; http://localhost:32400/player/playback/stop?commandID=2&type=video <?xml version='1.0' encoding='utf-8'?> <Response code="2000" status="FrameworkException: Unable to find player with identifier a4fce505a07192a5-com-plexapp-android">   <Traceback>Traceback (most recent call last):   File "/app/usr/lib/plexmediaserver/Resources/Plug-ins-f7262c352/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request     result = f(**d)   File "/app/usr/lib/plexmediaserver/Resources/Plug-ins-f7262c352/System.bundle/Contents/Code/playerservice.py", line 50, in process_remote_command     raise FrameworkException('Unable to find player with identifier %s' % identifier) FrameworkException: Unable to find player with identifier a4fce505a07192a5-com-plexapp-android </Traceback> </Response>  `

**Comment by Hellowlol** [comment]
Hi!

This is a the error response that plex returns. For some reason it cant reach the client. Nothing i can do to fix this, we try to proxy the command if it fails for some reason but that doesnt always work. Do you have some more info in your log?
