### ISSUE TITLE
Don't understand the remap

### ISSUE THREAD

**Issue by grego31430** [Hellowlol/bw_plex#144]
Hi,
I don't uderstand how to do the remap setting.
I have Plex Server on my Windows, and I have intall the bw_plex on WSL2.
all is good, but when bw_plex process a file, an error occur and say "Can't access to file"
I have read in some issue that I need to configure the remaps setting, but I can't do it ...
Here is my remaps config :

```
# remaps can use used to location set a partial location
# this is usefull if bw_plex is running on another computer.
# the key is the path plex user and the value is the computer running
# bw_plex. Ex:
# /tvseries/ = W:\
[remaps]
/mnt/share/Series = \\\\192.168.1.254\\share
```

In plex, the series library is in : \\192.168.1.254\share\Series\Series_Name\Season_number\File
I have mount this folder in the /mnt/share/Series in WSL
What I doing wrong ?

**Comment by Hellowlol** [comment]
I don't know what you have done wrong but i think you have swapped the key and the value.

It should be:
path_used_by_plex = path_on_the_computer_running_bw_plex_to_reach_the_same_folder

I think you should use:
/mnt/share/Series/ = \\\\192.168.1.254\\\share\\Series\\

**Comment by grego31430** [comment]
I have try, but this doesn't work ...
For more informations: 
On my plex, the tv series library scan network folder : \\192.168.1.254\share\Series
![image](https://user-images.githubusercontent.com/22960003/104130785-0549d000-5373-11eb-9c4a-da25eebcfe60.png)
On the bw_plex, this network folder was mount in /mnt/share/Series

I have try :
/mnt/share/Series = \\192.168.1.254\share\Series\
/mnt/share = \\192.168.1.254\share
/mnt/share = \\\\192.168.1.254\\share
\\192.168.1.254\share\Series = /mnt/share/Series
\\192.168.1.254\share = /mnt/share

**Comment by Hellowlol** [comment]
try
```
\\\\192.168.1.254\\share\\Series\\ = /mnt/share/Series/
```

**Comment by grego31430** [comment]
Same ... 
![image](https://user-images.githubusercontent.com/22960003/104131536-2e6c5f80-5377-11eb-9b1e-cd3ec3e2583c.png)

**Comment by Hellowlol** [comment]
I dont know then. https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/misc.py#L781 You can use this function in a script to test if the path is ok

**Comment by grego31430** [comment]
i have solved this problem, I have create a plex server on the bw_plex, with a docker, and all is working !
thank you :)
