### ISSUE TITLE
Crashing when trying to find recap

### ISSUE THREAD

**Issue by mjohn314** [Hellowlol/bw_plex#20]
I've tried this on a few different files, and all are throwing this error... Is there something I'm missing with the setup?

> 2018-03-29 17:10:57,104 :: bw_plex :: DEBUG :: Checking if ##REDACTED## has a recap with phrase previously on, last season, last episode using subtitles
> ERROR:root:
> Traceback (most recent call last):
>   File "/root/src/bw-plex/bw_plex/plex.py", line 345, in prot
>     process_to_db(item)
>   File "/root/src/bw-plex/bw_plex/plex.py", line 136, in process_to_db
>     recap = has_recap(media, CONFIG.get('words'), audio=vid)
>   File "/root/src/bw-plex/bw_plex/misc.py", line 612, in has_recap
>     audio_recap = has_recap_audio(audio)
>   File "/root/src/bw-plex/bw_plex/misc.py", line 578, in has_recap_audio
>     result = r.recognize_sphinx(audio, keyword_entries=[(i, thresh) for i in phrase])
>   File "/usr/local/lib/python2.7/dist-packages/speech_recognition/__init__.py", line 806, in recognize_sphinx
>     raise UnknownValueError()  # no transcriptions available
> UnknownValueError

**Comment by Hellowlol** [comment]
Thanks for the report. Ill fix that. :)

**Comment by Hellowlol** [comment]
I just pushed a fix.

**Comment by Hellowlol** [comment]
Let me know if it doesnt work :)
