### ISSUE TITLE
Create a minimal docker image

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/bw_plex#25]

**Comment by xasbo** [comment]
I had to manually install Visual C++ 9.0 manually (http://aka.ms/vcpython27) to make wsaccel happy. Everything else installed through pip just fine (or so it seemed).

What else is problematic?

**Comment by Hellowlol** [comment]
speech_recognition is usually the pain as you need swig in the cmd path. wsaccel isnt needed anymore as there is already a option to use numpy (as we need for other reasons), None if of this is "hard" but i want to lower the bar as much as possible. One other thing i that bw_plex need to be on the same local network as the client as we cant control it if not.

**Comment by sambrinck** [comment]
I started a centos based container [here](https://github.com/sambrinck/bw_plex) it installs succesfully but fails to run with an error: 
2018-09-11 04:30:57,582 :: bw_plex :: WARNING :: credits.py:19 :: Scanning for credits is not supported. Install the package with pip install bw_plex[all] or bw_plex[video]

if anyone has any ideas why it is failing we can fix it and add it to the baseline

**Comment by Hellowlol** [comment]
your trying to install the default package from git in addition to the one on pypi. Use
pip install -e git+https://github.com/Hellowlol/bw_plex.git#egg=bw_plex[all]

**Comment by McCloud** [comment]
Your docker image wasn't working for me, so I spent a couple hours finding the packages it needed, this seems to be working for a majority of my shows on a Roku.

https://hub.docker.com/r/mccloud/bw_plex/

**Comment by Hellowlol** [comment]
Thanks!
