### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'friendlyName'

### ISSUE THREAD

**Issue by chravtacque** [Hellowlol/bw_plex#39]
Hi there,

When running bw_plex I get the following error: `AttributeError: 'NoneType' object has no attribute 'friendlyName'`

console:
`chravtacque@DESKTOP-IRNQD9C:~/.local/bin$ /home/chravtacque/.local/bin/bw_plex watch`
`2018-06-03 06:53:47,465 :: bw_plex :: DEBUG :: Getting hashtable`
`2018-06-03 06:53:47,673 :: bw_plex :: INFO :: Creating new hashtable db `
`2018-06-03 06:53:47,674 :: bw_plex :: DEBUG :: Saving HashTable `
`Traceback (most recent call last):`
 ` File "/home/chravtacque/.local/bin/bw_plex", line 11, in <module>`
  `  sys.exit(cli())`
`  File "/home/chravtacque/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__`
`    return self.main(*args, **kwargs)`
`  File "/home/chravtacque/.local/lib/python2.7/site-packages/click/core.py", line 697, in main`
`    rv = self.invoke(ctx)`
`  File "/home/chravtacque/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke`
`    return _process_result(sub_ctx.command.invoke(sub_ctx))`
`  File "/home/chravtacque/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke`
`    return ctx.invoke(self.callback, **ctx.params)`
`  File "/home/chravtacque/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke`
`    return callback(*args, **kwargs)`
`  File "/home/chravtacque/.local/lib/python2.7/site-packages/bw_plex/plex.py", line 859, in watch`
`    click.echo('Watching for media on %s' % PMS.friendlyName)`
`AttributeError: 'NoneType' object has no attribute 'friendlyName'`

Any ideas on how to fix this?

**Comment by Hellowlol** [comment]
This means that PMS is None. You need to edit the config file or to pass the url and token.
bw_plex --url "http://xxxxxx:yyy" -t asdasdasd watch

**Comment by chravtacque** [comment]
Nice, thanks, that fixed the issue.

**Comment by Hellowlol** [comment]
I’ll add a clearer error message.
