### ISSUE TITLE
Remote Server/Compatible clients?

### ISSUE THREAD

**Issue by ersan** [Hellowlol/bw_plex#44]
I have a remote Plex server and am running bw_plex on a (Windows 10) computer on my local network.

It's saying it is calling the jump but nothing is happening
```
2018-06-18 15:09:19,005 :: bw_plex :: DEBUG :: Called jump with <bw_plex.db.Processed object at 0x000000001FE23668> 632 28.4212244898 None
2018-06-18 15:09:19,005 :: bw_plex :: DEBUG :: Called client_action with 28.4212244898 00:28 632 None
2018-06-18 15:09:19,066 :: bw_plex :: DEBUG :: client Bedroom 9
```

Apple TV is my primary client but I figured maybe it didn't work so I tried some others
PMP on macOS and Windows (the machine running bw_plex), Plex/Web via Safari and Chrome, Plex on iOS, Plex for Kodi.

Are any of these clients supported or am I doing something wrong?  I know having remote clients doesn't work but does a remote server not work either?

**Comment by Hellowlol** [comment]
I have tested this on iOS (iPhone, had to reboot iPhone first), openpht, plex web (buggy). I did a real quick test on one of the pmp modes, I can’t remember which and it worked (it was like a one sec test) I don’t have a remote server to test with. Any change you can install pms on the same computer that has bw_plex installed?

**Comment by ersan** [comment]
I might be able to later but I don't store media locally.  When you call the jump is that a command sent to the server or directly to a client?  My PMS has no way of reaching my clients (firewall, shared ports, etc), unless the clients maintain some sort of connection with the server waiting for commands like this.

**Comment by Hellowlol** [comment]
I’m pretty sure I try to send the command via pms. If you dont mind getting you hands dirty you can try to comment out https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/plex.py#L711

**Comment by ersan** [comment]
Tried commenting that, didn't make a difference.  No worries, though - I think having a remote PMS is not a common setup.

**Comment by Hellowlol** [comment]
I’ll look into it. :)

**Comment by ersan** [comment]
I think the remote control command you send to PMS uses Plex Companion, so the PMS has to be able to access your client somehow.  On the [port forwarding page for plex](https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/) it shows the companion ports for PHT (discontinued) and Roku - neither of which I have, but none of the other clients.  Old help page needs to be updated.  Either way if it uses the same port on each device it's not going to work because of NAT, and PMS isn't going to be aware of the LAN IP for the client in question so bw_plex won't be able to contact the client directly anyway without a lot of effort.

Remote servers (and remote clients) should probably work fine then if the correct ports are open.

**Comment by Hellowlol** [comment]
So i have started on a wiki to document what client works. If you want to test this your should include do ``` bw_plex --debug watch``` as this includes the httpcalls so it easier for see why something fails. If you ca verify a new client please update the wiki.

**Comment by Hellowlol** [comment]
Closing this. If you verify that a client works. please update the wiki.
