### ISSUE TITLE
Skip not sending correctly in Firefox client

### ISSUE THREAD

**Issue by Velkas** [Hellowlol/bw_plex#49]
Server Environment:
Windows 10 Pro 1709 16299.492
Plex Media Server 1.13.5.5291

Client Environment:
Windows 10 Pro 1709 16299.492
Firefox 61.0.1 (64-bit)

bw_plex Environment:
Windows 10 Pro 1709 16299.492
bw_plex 0.0.9.dev2+g35b90c3

General Environment Details:
PMS Server, Client and bw_plex are running from the same machine.

Problem:
After starting bw_plex, then starting a show, it properly finds and updates the client info in the log, then attempts to send the skip command. However the skip doesn't happen.

Log during skip event: 
```2018-08-03 23:35:15,459 :: bw_plex :: DEBUG :: plex.py:886 :: The.Office.(US).s01e02 is in the correct time range theme_end
2018-08-03 23:35:15,461 :: bw_plex :: DEBUG :: plex.py:846 :: Called jump with The.Office.(US).s01e02 5 27.376326530612246 None
2018-08-03 23:35:15,463 :: bw_plex :: DEBUG :: plex.py:654 :: Called client_action with 27.376326530612246 00:27 5 None
2018-08-03 23:35:15,993 :: bw_plex :: DEBUG :: plex.py:687 :: client Firefox 9.0

**Comment by Velkas** [comment]
Addition:
After running for a couple hours and watching more episodes of a show, the log suddenly changed the firefox version?

```2018-08-04 01:05:26,444 :: bw_plex :: DEBUG :: plex.py:886 :: The.Office.(US).s01e05 is in the correct time range theme_end
2018-08-04 01:05:26,445 :: bw_plex :: DEBUG :: plex.py:846 :: Called jump with The.Office.(US).s01e05 9 27.329886621315193 None
2018-08-04 01:05:26,446 :: bw_plex :: DEBUG :: plex.py:654 :: Called client_action with 27.329886621315193 00:27 9 None
2018-08-04 01:05:26,973 :: bw_plex :: DEBUG :: plex.py:687 :: client Firefox 23.0

**Comment by Hellowlol** [comment]
It’s really strange that the firefox version should change. You should start bw_plex with —debug so additional logging is enabled. Maybe that can shed some light why it isn’t sending the seek command.

**Comment by Velkas** [comment]
Yeah I was confused by that. Started up watching again tonight and it changed to Firefox 6.0. Still not skipping. However, it was skipping (really felt like magic!) while watching remotely on my iPhone today while I was out. So this is a fantastic project. I'll try to get more debug info shortly and let you know. Random aside, do you plan on making this a plug-in level app for plex, if that's even possible?

**Comment by Hellowlol** [comment]
Nope, Plex addon system is too restricted :(

**Comment by Hellowlol** [comment]
Did you enable more logging?

**Comment by Hellowlol** [comment]
Closed for inactivity
