### ISSUE TITLE
wavfile2peaks: Error reading file skipping ... python stuck indefinitely 

### ISSUE THREAD

**Issue by JourneyOver** [Hellowlol/bw_plex#5]
Posted this on reddit, but just thought I'd post here as well.. 

running plex_jump.py create_hash_table_from_themes I end up seeming to throw an error and then python just hangs indefinitely..
```
2018-01-02 12:33:54,628 :: F:\Misc\bw_plex\plex_jump.py :: INFO :: Loading existing files in db
Read fprints for 0 files ( 0 hashes) from F:\Misc\bw_plex\hashes.pklz (0.00% dropped)
Error reading header info from F:\Misc\bw_plex\themes\Channel Zero__5826.mp3
wavfile2peaks: Error reading F:\Misc\bw_plex\themes\Channel Zero__5826.mp3 skipping
Process Process-1:
Traceback (most recent call last):
  File "C:\Tools\python2\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Tools\python2\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Misc\bw_plex\audfprint\audfprint.py", line 128, in make_ht_from_list
    hashes = analyzer.wavfile2hashes(filename)
  File "F:\Misc\bw_plex\audfprint\audfprint_analyze.py", line 408, in wavfile2hashes
    self.peaks2landmarks(peaklist)))
  File "F:\Misc\bw_plex\audfprint\audfprint_analyze.py", line 88, in landmarks2hashes
    hashes[:, 0] = landmarks[:, 0]
IndexError: too many indices for array
```

**Comment by Hellowlol** [comment]
Thanks alot for the feedback. Ill took into it. Thanks alot for testing. As i mentioned in the thread this is alpha xD. Can you just delete the theme and try some other files?

**Comment by JourneyOver** [comment]
So I ran into the issue 3 seperate times for my list on what the program at least pulled in.. (it missed several shows when doing the "update_all_themes" bit)

anyways the 3 shows that at least the above error hit with are these
Channel Zero
The Magicians (2015)
Love, Chunibyo & Other Delusions

Once they where removed the "create_hash_table_from_themes" seems to have succeeded.

**Comment by Rocketcandy** [comment]
I am also having the problem, but it doesn't seem to be updating any of mine, it starts to build the list, but when it hits a show that has a space it says no such file or directory.

```
[Errno 2] No such file or directory
wavfile2peaks: Error reading /home/inver/bw_plex/themes/The Expanse__203745.mp3 skipping
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/inver/bw_plex/audfprint/audfprint.py", line 128, in make_ht_from_list
    hashes = analyzer.wavfile2hashes(filename)
  File "/home/inver/bw_plex/audfprint/audfprint_analyze.py", line 408, in wavfile2hashes
    self.peaks2landmarks(peaklist)))
  File "/home/inver/bw_plex/audfprint/audfprint_analyze.py", line 88, in landmarks2hashes
    hashes[:, 0] = landmarks[:, 0]
IndexError: too many indices for array
```

**Comment by Hellowlol** [comment]
@Rocketcandy It should handle spaces in filenames just fine. I guess the file is broken somehow. Can you open the mp3 in a problem and check if it ok? (just open in vlc or something like that)
I need to add some errors handles. So this does not stop the entire program.

**Comment by Rocketcandy** [comment]
[The Expanse__203745.zip](https://github.com/Hellowlol/bw_plex/files/1605121/The.Expanse__203745.zip)

It plays just fine in VLC.

**Comment by JourneyOver** [comment]
yea that's what was happening to me as well, the files would work in VLC/other players just fine but bw_plex would still end up throwing the IndexError anyways.

**Comment by sirelewop14** [comment]
Just thought I would drop in on this issue too, as I have seen it this morning.

Got things installed on Unbuntu today and started setting up.

Noticed this when building hash table.

`[Errno 2] No such file or directory
wavfile2peaks: Error reading /home/rhys/bw_plex/themes/Uncle Grandpa__9627.mp3 skipping
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rhys/bw_plex/audfprint/audfprint.py", line 128, in make_ht_from_list
    hashes = analyzer.wavfile2hashes(filename)
  File "/home/rhys/bw_plex/audfprint/audfprint_analyze.py", line 408, in wavfile2hashes
    self.peaks2landmarks(peaklist)))
  File "/home/rhys/bw_plex/audfprint/audfprint_analyze.py", line 88, in landmarks2hashes
    hashes[:, 0] = landmarks[:, 0]
IndexError: too many indices for array
^C
Aborted!`

`[Errno 2] No such file or directory
wavfile2peaks: Error reading /home/rhys/bw_plex/themes/The Orville__16533.mp3 skipping
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rhys/bw_plex/audfprint/audfprint.py", line 128, in make_ht_from_list
    hashes = analyzer.wavfile2hashes(filename)
  File "/home/rhys/bw_plex/audfprint/audfprint_analyze.py", line 408, in wavfile2hashes
    self.peaks2landmarks(peaklist)))
  File "/home/rhys/bw_plex/audfprint/audfprint_analyze.py", line 88, in landmarks2hashes
    hashes[:, 0] = landmarks[:, 0]
IndexError: too many indices for array
^C
Aborted!
`

I removed all file names with spaces in them, but still had the same issue with files that had no space in names.

**Comment by sirelewop14** [comment]
New development, it appears my Ubuntu VM did not have ffmpeg installed on it.
I noticed this when running the watcher in debug mode, it would call for a convert to .wav using ffmpeg, but no output would ever show up in /tmp/

I installed ffmpeg, and now when running the hash table generation step, it appears to be working. Will report back when it completes to confirm if it was successful or not.

I had also noticed I needed to install python-tk to get things running, this had already been mentioned on reddit, but it is probably worth noting the documentation that python-tk and ffmpeg are needed for this code to work.

**Comment by JourneyOver** [comment]
It shouldn't be something to do with ffmpeg as I had that installed when it was throwing this error, but it could be about missing python-tk as I believe I didn't have that.. But I myself am not to worried about this anyways now as I pretty much gave up on this script for the time being since it doesn't work for plex web player at all currently.

**Comment by Hellowlol** [comment]
Thanks a lot for testing. As I mention in the Reddit thread this is alpha software, there is little to no error handling atm.

The todo list is:
- find a way to get better themes as most of them to too bad to match. 
- config and logging to a file.
- add cli option to print the db
- error handling
- packaging 
- and maybe in the future add a option to skip credits

**Comment by Hellowlol** [comment]
So i haven't fixed the errors that you have experienced.  However i have uploaded this as a package to pypi so its easier to install. We download the themes from youtube instead of plex. While they are generally alot better we might still mess up and select the wrong theme. If thats the case fixit by running the fix_shitty_theme command

**Comment by Hellowlol** [comment]
I hope this should be fixed now. Make sure you do a fresh pull. If it’s still a issue feel free to reopen.
