### ISSUE TITLE
bw_plex command not found, installed perfectly

### ISSUE THREAD

**Issue by CKyle22** [Hellowlol/bw_plex#50]
bw_plex installed just fine, but I get `bw_plex: command not found` when I try to run it. Running Ubuntu 18.04 LTS.

**Comment by Hellowlol** [comment]
Did you install from source or pypi? what happens if you do python -m bw_plex?

**Comment by CKyle22** [comment]
I installed it just like it says on the main page, `pip install -e git+https://github.com/Hellowlol/bw_plex.git#egg=bw_plex`

`python -m bw_plex` seems to work, though.

**Comment by Hellowlol** [comment]
I have no idea why the entry point doesn’t work. It works just fine in the docker and Travis. Anyway just use the other method.
