### ISSUE TITLE
bw_plex watch not working

### ISSUE THREAD

**Issue by MitjaHenner** [Hellowlol/bw_plex#53]
bw_plex watch seems to start fine, but then does nothing. I guess it should at least show something in the debug log when I start to play something right?
```
2018-08-30 01:00:59,757 :: bw_plex :: DEBUG :: misc.py:63 :: Getting server Plex-Server
2018-08-30 01:00:59,757 :: bw_plex :: DEBUG :: misc.py:584 :: Getting hashtable
2018-08-30 01:01:02,257 :: bw_plex :: INFO :: misc.py:670 :: Loading existing files in db
2018-08-30 01:01:06,023 :: bw_plex :: DEBUG :: misc.py:599 :: Files in the hashtable
Watching for media on Plex-Server
2018-08-30 01:01:06,023 :: plexapi :: INFO :: alert.py:33 :: Starting AlertListener: wss://192.168.0.20:32400/:/websockets/notifications?X-Plex-Token=<hidden>

```

Windows 10 x64
Python 3.7 x64

**Comment by Hellowlol** [comment]
Hi! Try starting bw_plex with --debug this is disable to reduce spam in the log but since nothing else is listed on the log we need to get more info.

**Comment by MitjaHenner** [comment]
This is a debug log.

Which version should I use?

**Comment by Hellowlol** [comment]
Try 3.6

**Comment by MitjaHenner** [comment]
Same problem with 3.6, anything else I can try or some other logs I can post?

**Comment by Hellowlol** [comment]
What the full Vollane you use to start bw_plex? 

Try bw_plex process -n showname

**Comment by MitjaHenner** [comment]
Processing seems to work fine. Tested with Friends 1x01 but still nothing triggered when I start playing the episode.

**Comment by Hellowlol** [comment]
Dunno mate. You need to do bw_plex -d watch. This enabled not just debug logging in bw_plex but also additional logging from package bw_plex uses. (You havnt done this or havnt provided the full log. Warning this will not sanitize the log for you so you need to do this your self)

**Comment by Hellowlol** [comment]
check what version of websocket-client you have installed. I think your issue is related to that. Im using websocket-client 0.47. try to install that one.

**Comment by MitjaHenner** [comment]
With version 0.47 Im getting a debug log. It seems to skip on the local PMP install. Not getting the intro right, but with the log I can at least try to get it working. Reporting back tomorrow.

**Comment by Hellowlol** [comment]
Any news about this?
