### ISSUE TITLE
Shorten time between ticks

### ISSUE THREAD

**Issue by epsicola** [Hellowlol/bw_plex#55]
Hello, first off, loving this project. Took me 4 hours to get it running but it's pretty sweet now that it is. 

I was hoping there could be an option to shorten the time between websocket ticks. Right now, it's  every 10 seconds but some theme songs are like 20 seconds long so you sometimes have to sit through half of it before it gets skipped. 

Any help with this would be greatly appreciated.

**Comment by Hellowlol** [comment]
We can’t shorten the tick. That part is controlled from plex. See https://github.com/Hellowlol/bw_plex/issues/24

**Comment by Hellowlol** [comment]
It wouldn’t be to hard. Basically we check if the start will happen before the next tick. If it does we will manually fire the jump before we reach the tick.

**Comment by epsicola** [comment]
Oh ok, so it's not something I can do.

**Comment by Hellowlol** [comment]
I’ll get this done eventually:)

**Comment by Hellowlol** [comment]
I have added a simple way to fool the progress. Can you try to edit no_wait_tick (in the config) to like 5 or seven and see if this helps
