### ISSUE TITLE
Where is the default folder?

### ISSUE THREAD

**Issue by GodsVictory** [Hellowlol/bw_plex#56]
I keep getting an error message saying the default folder is not writeable, but nothing telling me where that folder is.

**Comment by Hellowlol** [comment]
That depends. You can change it or relative to your Home folder see 
https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/__init__.py#L113

**Comment by Hellowlol** [comment]
Also the default location is in the log.

**Comment by GodsVictory** [comment]
If the directory doesn't exist you don't get any log messages

After creating it I started seeing proper error messages

**Comment by Hellowlol** [comment]
Thats strange. It should be create the default folder

https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/__init__.py#L126

**Comment by Hellowlol** [comment]
zomg, i can see the bug :D
