### ISSUE TITLE
ValueError: unsupported pickle protocol: 4 

### ISSUE THREAD

**Issue by budgidiere** [Hellowlol/bw_plex#63]
I get: 
ValueError: unsupported pickle protocol: 4
Whenever I run bw_plex

**Comment by Hellowlol** [comment]
That usually means that you ran bw_plex on Python versoon higher the 3.4 and are now trying to use 2.7. Delete the hashes.plkz file and start it again. Stick with one version :) (use python3)

**Comment by budgidiere** [comment]
Thanks, @Hellowlol ! as soon is I fixed that I got another error: AttributeError: 'NoneType' object has no attribute 'friendlyName'

**Comment by Hellowlol** [comment]
Are are not connected to PMS edit the config or pass the url and token using the cli
