### ISSUE TITLE
Could the README be updated to include which flags are required

### ISSUE THREAD

**Issue by CDeLeon94** [Hellowlol/bw_plex#90]
I'm probably going to just try adding everything and then removing one at at time to see which are required. But I think the README should include this information.

**Comment by Hellowlol** [comment]
Nothing is required except for the info needed to authenticate against pms. The best solution is to use the config file and set the url and the token.

If not you need to do ‘’’’bw_plex —url “http://...” -t “pmstoken” command’’’’ I’ll update the readme. Thanks for the suggestion.

**Comment by Hellowlol** [comment]
Done in 26787cf5c042c2f13cb25cc842b0b9a33b5ee7bc
